language: r
sudo: true
dist: trusty
cache: packages
warnings_are_errors: false
addons:
  packages:
    - ghostscript
r: bioc-devel
r_packages:
  - devtools
  - covr
before_install:
  - sudo apt-get -y --reinstall install ghostscript
  - tlmgr install bera nowidow parnotes marginfix etoolbox titlesec sectsty framed enumitem parskip soul placeins footmisc changepage xstring caption mathtools
after_success:
  - Rscript -e 'covr::codecov()'
